---
- hosts: all
  become: true
  vars:
    container_count: 2
    default_container_name: docker
    default_container_image: ubuntu
    default_container_command: sleep 1
    username: team2_user
    folder_path: /home/{{ username }}/team2_repo
  roles:
  #- users
  #- install_docker #runs updated and installs docker
   - download_git_repository
   # - run_mysql
    #- run_python
    #- restore_mysql
